### PR TITLE
fix(App): use an environment variable for socket.io server address

### PR DESCRIPTION
**Pull request by hissalht**
Instead of hardcoding the server URL, we get it from an environment variable called `REACT_APP_SOCKETIO_URL`. If the variable is not set, we use the current origin as a default.

We also configure the dev-server to proxy requests to our own socket-io server running locally.

### CODE REVIEW

**Comment by quantumproducer** [comment]
@hissalht being able to control the server address is good. Using `window.location.origin` would require the development server modification like you said. You could add a default port option to this PR, defaulting to port 8000, and that should work for development + production.

The socket code on wiz-server is something that needs to be reviewed and might change so I favor a simpler solution of having a port ENV + default on the client.

**Comment by hissalht** [comment]
Since the wizard server is not CORS-enable (and does not need to), I removed the optionnal `REACT_APP_SOCKETIO_URL` variable and just use window.location.origin.

It should work both in production and development. 
In development, it's assumed the wiz-server is running on it's default port locally.

**Comment by hissalht** [comment]
> @hissalht hey, I tried running https://github.com/hissalht/wiz-client/tree/fix-hardcoded-ip
> 
> yarn start
> yarn run v1.10.1
> $ react-scripts start
> /bin/sh: react-scripts: command not found
> error Command failed with exit code 127.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> ~/brik-wiz/
> 
> yarn start needs to be working again for this pull

@quantumproducer 
Install the dependencies with `$ yarn install`

**Comment by quantumproducer** [comment]
@hissalht :facepalm: I didn't even check, sorry! I will test this today.

**Pull request merged**
